sudo: required
services:
  - docker

before_install:
  - docker build -t nickrockstar/docker-react -f Dockerfile.dev .

script:
  - docker run nickrockstar/docker-react npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: 'eu-central-1'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-eu-central-1-991607386664'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
